# fly.toml app configuration file generated for pokedex-fso-danderson on 2025-10-15T09:04:46-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pokedex-fso-danderson'
primary_region = 'iad'

[build]

[env]
  PORT = "3000"

[processes]
  app = "node app.js"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[deploy]
  strategy = "canary"

[[vm]]
  size = 'shared-cpu-1x'
