# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Deployment pipeline
on:
  push:
    branches:
      - main

  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  check_commit_messages_for_skip:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.check.outcome == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - if: ${{ contains(join(fromJson(toJson(github.event.commits)).*.message, ' | '), '#skip') }}
        id: check
        run: echo

  simple_deployment_pipeline:
    needs: [check_commit_messages_for_skip]
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time for the specified group
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run eslint

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to fly
        if: ${{ github.event_name == 'push' && needs.check_commit_messages_for_skip.outputs.status != 'true' }}
        run: flyctl deploy --remote-only --ha=false
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  tag_release:
    needs: [check_commit_messages_for_skip, simple_deployment_pipeline]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && needs.check_commit_messages_for_skip.outputs.status != 'true' }}
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: 'patch'
          INITIAL_VERSION: 0.0.0
          # DRY_RUN: true

  notify_discord:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    steps:
      - name: Notify success
        uses: sarisia/actions-status-discord@v1
        if: success()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          content: A new version of Pokedex deployed
          status: ${{ needs.simple_deployment_pipeline.result }}
          title: 'Deploy'
          color: 0x00FF00
          username: GitHub
          avatar_url: ${{ secrets.GH_AVATAR_URL }}

      - name: Notify failure
        uses: sarisia/actions-status-discord@v1
        if: failure()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          content: Build failed
          status: ${{ needs.simple_deployment_pipeline.result }}
          title: 'Deploy'
          color: 0xFF0000
          username: GitHub
          avatar_url: ${{ secrets.GH_AVATAR_URL }}
