name: Testing
on:
  push:
    branches:
      - main

  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  check_commit_messages_for_skip:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.check.outcome == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - if: ${{ contains(join(fromJson(toJson(github.event.commits)).*.message, ' | '), '#skip') }}
        id: check
        run: echo

  explore_github_context:
    needs:
      - check_commit_messages_for_skip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ join(fromJson(toJson(github.event.commits)).*.message, ' | ') }}
        run: echo "$COMMIT_MESSAGES"

      - name: confirm skip
        if: ${{ needs.check_commit_messages_for_skip.outputs.status == 'true' }}
        run: echo "#skip confirmed"
