name: Testing
on:
  push:
    branches:
      - main

  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  explore_github_context:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ fromJson(toJson(github.event.commits)).*.message }} # The .*. (wildcard) selector isn't supported inside ${{ ... }} -- GitHub Actions expressions don't allow you to map or iterate over arrays directly like that.
        run: echo "$COMMIT_MESSAGES"
