name: Testing
on:
  push:
    branches:
      - main

  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  explore_github_context:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: github.event.commits + github.event.commits.*.message
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: |
          echo "All commits JSON:"
          echo "$COMMITS"

          echo "Extracted messages:"
          echo "$COMMITS" | jq -r '.[].message'
